# -*- coding: utf-8 -*-
"""
Resource definitions for Auto Georeferencer plugin
"""

# Resource file - normally generated by pyrcc5, but we'll create a simple version
def qInitResources():
    pass

def qCleanupResources():
    pass
